---
title: Знакомство с линейными моделями (с основами R)
description: Презентации к курсу
---
 
## О курсе

Задача курса познакомить слушателей с одним из самых важных инструментов обработки научных данных --- статистическими методами, основанными на линейных моделях (регрессионный, дисперсионный, ковариационный анализы). По мере освоения курса, в режиме погружения, планируется обсуждение большого круга смежных вопросов, таких как планирование экспериментов, представление первичной информации в формате, доступном для экспертной оценки, и визуализация результатов. Центральная особенность курса – это использование для изложения материала возможностей языка статистического программирования R. Знакомство с этим мощным средством позволит слушателям организовать свою работу в стиле воспроизводимого исследования (reproducibleresearch), что является одним из ключевых требований к современной исследовательской работе.

### Контакты

- Варфоломеева Марина Александровна -  marina.varfolomeeva[]gmail.com
- Хайтов Вадим Михайлович - polydora[]rambler.ru
- Тамберг Юта Юрьевна - yutamberg[]gmail.com

## Ссылки и ресурсы

- [Исходный код в RMarkdown](http://github.com/varmara/glmintro)
- [Другие ресурсы и книги для изучения R и статистики](resources.html)

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->

