---
title: Презентации и данные
---

## День 1

### Планирование экспериментов

- Презентация [pdf](1.1_experimental_design.pdf)

### Знакомство с R

- Презентация [html](1.2_introduction.html)
- Код [1.2_introduction_code.R](1.2_introduction_code.R)
- Данные [1.2_temperature.csv](data/1.2_temperature.csv)

Дополнительные материалы:

- [Cheat-sheet по RStudio](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf) от [RStudio](https://www.rstudio.com)
- Очень краткая шпаргалка по R [Cheat-sheet по базовому R](http://www.rstudio.com/wp-content/uploads/2016/06/r-cheat-sheet.pdf) от [Mhairi McNeill](http://mhairihmcneill.com/)
- Более подробная шпаргалка [R reference card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf) от Tom Short
- [Data import cheat-sheet](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-import-cheatsheet.pdf)

### Графики в R

- Презентация [html](1.3_intro_ggplot.html)
- Код [1.3_intro_ggplot.R](1.3_intro_ggplot.R)
- Данные [fev.xls](data/fev.xls)

Дополнительные материалы:

- [Cookbook for R](http://www.cookbook-r.com/) --- сайт [книги Winston Chang](http://www.amazon.com/gp/product/0596809158/ref=as_li_tf_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0596809158&linkCode=as2&tag=cooforr09-20)
- [Руководство по ggplot2](http://ggplot2.tidyverse.org/reference/)
- [Cheat-sheet по ggplot2](https://github.com/rstudio/cheatsheets/raw/master/old/pdfs/ggplot2-cheatsheet-2.1.pdf)
 от [RStudio](https://www.rstudio.com)
- [ggplot2 Quick Reference: colour and fill](http://sape.inf.usi.ch/quick-reference/ggplot2/colour)
- [ggplot2 Quick reference: shape](http://sape.inf.usi.ch/quick-reference/ggplot2/shape)

## День 2

### Описательная статистика

- Презентация [2.1_descriptive_statistics.html](2.1_descriptive_statistics.html)
- Код [2.1_descriptive_statistics_code.R](2.1_descriptive_statistics_code.R)
- Данные [2.1_diatome_count.csv](data/2.1_diatome_count.csv)

### Тестирование гипотез

- Презентация [2.2_hypothesis_testing.html](2.2_hypothesis_testing.html)
- Код [2.2_hypothesis_testing_code.R](2.2_hypothesis_testing_code.R)
- Данные [data/2.2_aml.csv](data/2.2_aml.csv)

### Анализ мощности

- Презентация [2.3_power.html](2.3_power.html)
- Код [2.3_power_code.R](2.3_power_code.R)
- Данные
    + [remission.xlsx](data/remission.xlsx)
    + [urine.xlsx](data/urine.xlsx)
    + [Cushings.xlsx](data/Cushings.xlsx)

### Множественное тестирование

- Презентация [2.4_multiple_comparisons.html](2.4_multiple_comparisons.html)
- Код [2.4_multiple_comparisons_code.R](2.4_multiple_comparisons_code.R)
- Данные [fake_expression_samples.csv](data/fake_expression_samples.csv)

## День 3

### Оценка взаимосвязей: корреляция, линейная регрессия

- Презентация [3.2_lm.html](3.2_lm.html)
- Код [3.2_lm_exerc.R](3.2_lm_exerc.R)
- Данные
    + [hellung.xls](data/hellung.xls)
    + [secher.xls](data/secher.xls)
    + [kfm.xls](data/kfm.xls)
    + [catsM.xlsx](data/catsM.xlsx)
- Упражненияb
    + [3.2_lm_exerc_2.R](3.2_lm_exerc_2.R)
    + [3.2_lm_exerc_3.R](3.2_lm_exerc_3.R)


### Условия применимости линейной регрессии

- Презентация [3.3_assumptions.html](3.3_assumptions.html)
- Код [3.3_assumptions_code.R](3.3_assumptions_code.R)
- Данные
    + [orly_owl_Lin_4p_5_flat.txt](data/orly_owl_Lin_4p_5_flat.txt)
    + [catsM.xlsx](data/catsM.xlsx)
    + [calcium.xlsx](data/calcium.xlsx)
    + [progesterone_Brutsaert_et al_2002_lm.xlsx](data/progesterone_Brutsaert_et al_2002_lm.xlsx)
    + [GAGurine.xlsx](data/GAGurine.xlsx)
    + [mutations_Kong_et_al_2012_lm_assumptions.xlsx](data/mutations_Kong_et_al_2012_lm_assumptions.xlsx)
- Упражнения (разбор готового кода)
    + [3.3_assumptions_Ex_calcium.R](3.3_assumptions_Ex_calcium.R)
    + [3.3_assumptions_Ex_progesteron.R](3.3_assumptions_Ex_progesteron.R)
- Упражнения (написание кода)
    + [3.3_assumptions_Task_GAG.R](3.3_assumptions_Task_GAG.R)
    + [3.3_assumptions_Task_Mutations.R](3.3_assumptions_Task_Mutations.R)

## День 4

### Множественная линейная регрессия

- Презентация [4.1_multiple_lm.html](4.1_multiple_lm.html)
- Код [4.1_multiple_lm_code.R](4.1_multiple_lm_code.R)
- Данные
    + [Prostate.xlsx](data/Prostate.xlsx)
    + [loyn.csv](data/loyn.csv)
    + [SAheart.xlsx](data/SAheart.xlsx)
- Упражнения (разбор кода) 
    + [4.1_multiple_lm_Ex_Loyn's_bird_data.R](4.1_multiple_lm_Ex_Loyn's_bird_data.R)
- Упражнения (написание кода) 
    + [4.1_multiple_lm_Task_SAheart.R](4.1_multiple_lm_Task_SAheart.R)

### Выбор моделей

- Презентация [4.2_model_selection.html](4.2_model_selection.html)
- Код [4.2_model_selection_code.R](4.2_model_selection_code.R)
- Данные
    + [Prostate.xlsx](data/Prostate.xlsx)
    + [loyn.csv](data/loyn.csv)
    + [SAheart.xlsx](data/SAheart.xlsx)
- Упражнения (разбор кода)
    + [4.2_model_selection_Ex_Loyn's_bird_data.R](4.2_model_selection_Ex_Loyn's_bird_data.R)
- Упражнения (написание кода)
    + [4.2_model_selection_Task_SAheart.R](4.2_model_selection_Task_SAheart.R)

## День 5

### Дискретные предикторы в регрессионных моделях

- Презентация <!-- []() --->
- Код []
- Данные
    + [vitcap2.csv](data/vitcap2.csv)
    + [goats.csv](data/goats.csv)
    + [fev.xls](data/fev.xls)
    + [cats.xlsx](data/cats.xlsx)
- Упражнения (разбор кода)
    + [5.1_no_interaction_Ex_fev.R](5.1_no_interaction_Ex_fev.R)
- Упражнения (написание кода)
    + [5.1_no_interaction_Task_cats.R](5.1_no_interaction_Task_cats.R)

### Взаимодействие дискретного и непрерывного предикторов

- Презентация <!-- [5.2_categorical-continuous_interaction.html](5.2_categorical-continuous_interaction.html) --->
- Код []
- Данные
    + [Puromycin.xlsx](data/Puromycin.xlsx)
    + [nitrofen.xlsx](data/nitrofen.xlsx)
    + [fev.xls](data/fev.xls)
    + [cats.xlsx](data/cats.xlsx)
- Упражнения (разбор кода)
    + [5.2_interactions_Ex_fev.R](5.2_interactions_Ex_fev.R)
- Упражнения (написание кода)
    + [5.2_interactions_Task_cats.R](5.2_interactions_Task_cats.R)

## День 6

### Практикум по анализу данных

- Данные
- Упражнения (написание кода)
    + []()
- Упражнения (разбор кода)
    + []()


